#!/usr/bin/env python3

import json
import posix_ipc
import sys

event=sys.argv[1]
if len(sys.argv) == 2:
	mq=posix_ipc.MessageQueue("/alfredio") 
	mq.send(json.dumps({"name":event,"data":""}))
else :
	mq=posix_ipc.MessageQueue("/alfredio") 
	mq.send(json.dumps({"name":event,"data":json.load(sys.argv[2])}))
